-- the total revenue generated by google traffic on an ecommerce site
-- What is the total transaction_revenue that customers via the google traffic_source have brought in?
WITH clean_sessions AS (
  SELECT date,
  user_cookie_id, user_crm_id, session_id, traffic_source, traffic_medium, device_category, city
  FROM (
    SELECT *,
    RANK() OVER(PARTITION BY session_id ORDER BY date DESC) AS rank_number
    FROM `prism_sync.sessions`
  ) AS ranked_sessions
  WHERE ranked_sessions.rank_number = 1
)


SELECT SUM(transaction_revenue) AS google_transaction_revenue
FROM `prism_sync.transactions` transactions
JOIN clean_sessions
ON transactions.session_id = clean_sessions.session_id
where traffic_source = 'google';

WITH sessions_deduplicated AS (SELECT DISTINCT session_id, traffic_source FROM `prism_sync.sessions`)

-- 5734482.9074999988
SELECT traffic_source, SUM(transaction_revenue) transaction_revenue
FROM sessions_deduplicated s
JOIN `prism_sync.transactions` t
ON s.session_id = t.session_id
GROUP BY traffic_source
ORDER BY transaction_revenue DESC